#!/usr/bin/env bash
# Rocketman PreToolUse guard — enforces the golden rule at the tool level:
# "Edit the data, never the HTML."
#
# Claude Code calls this before a Write/Edit. It receives the tool call as JSON
# on stdin (with .tool_input.file_path). If the target is a generated artifact,
# we exit 2 to BLOCK the call and tell the model to edit PM/data/*.json instead.
#
# Wired via each data-writing skill's frontmatter:
#   hooks:
#     PreToolUse:
#       - matcher: "Write|Edit"
#         hooks:
#           - type: command
#             command: 'bash "${CLAUDE_PROJECT_DIR:-.}/.claude/hooks/guard-generated.sh"'
#
# Zero dependencies beyond bash. jq used if present; falls back to grep.

set -euo pipefail
payload="$(cat 2>/dev/null || true)"

# Extract the target file path from the tool-call JSON.
path=""
if command -v jq >/dev/null 2>&1; then
  path="$(printf '%s' "$payload" | jq -r '.tool_input.file_path // .tool_input.path // empty' 2>/dev/null || true)"
fi
if [ -z "$path" ]; then
  # Fallback: pull the first file_path-looking value out of the raw JSON.
  path="$(printf '%s' "$payload" | grep -oE '"file_path"[[:space:]]*:[[:space:]]*"[^"]+"' | head -1 | sed -E 's/.*:[[:space:]]*"([^"]+)"/\1/' || true)"
fi

case "$path" in
  */PM/index.html|PM/index.html)
    echo "BLOCKED: PM/index.html is generated by 'rocketman build'. Do not edit it directly." >&2
    echo "Edit the data in PM/data/*.json (or PM/comms/* for the relay), then run: rocketman build" >&2
    exit 2
    ;;
esac

exit 0
